[package]
name = "risico-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
chrono = "0.4"
serde = "1.0"
libflate = "1.2.0"
netcdf = "0.7.0"
rayon = "1.6.0"
ndarray = "0.15.6"
png = "0.17.7"