models:
  - type: RISICO
    model_name: RISICO2023
    static_data:
      type: geotiff
      domain_mask: /opt/risico/RISICO2023/STATIC/geotiff/domain_mask.tif
      slope: /opt/risico/RISICO2023/STATIC/geotiff/slope.tif
      aspect: /opt/risico/RISICO2023/STATIC/geotiff/aspect.tif
      vegetation_id: /opt/risico/RISICO2023/STATIC/geotiff/vegetation_id.tif
      vegetation_catalog: /opt/risico/RISICO2023/STATIC/p_vegetazione.csv
      ppf_summer: null
      ppf_winter: null
    warm_state:
      type: netcdf
      directory: /opt/risico/RISICO2023/STATE0/netcdf
      max_age_hours: 120
      on_missing: error
    output_types:
      - internal_name: RISICO2023
        name: RISICO2023
        path: /opt/risico/RISICO2023/OUTPUT-NC/
        grid_path: /opt/risico/RISICO2023/GRID/RISICOGRID.txt
        format: NETCDF
        variables:
          - internal_name: V
            name: V
            cluster_mode: Max
            precision: 0
    palettes:
      UMB: /opt/risico/PALETTE/RISICO_UMB.pal
    output_time_resolution: 1
    model_version: v2023
    netcdf_input_configuration: null

  - type: FWI
    model_name: FWIITALIA
    static_data:
      type: geotiff
      domain_mask: /opt/risico/RISICO2023/STATIC/geotiff/domain_mask.tif
    warm_state:
      type: netcdf
      directory: /opt/risico/RISICO2023/STATE0/netcdf-fwi
      max_age_hours: 120
      on_missing: error
    output_types:
      - internal_name: RISICO2023
        name: RISICO2023
        path: /opt/risico/RISICO2023/OUTPUT-NC/
        grid_path: /opt/risico/RISICO2023/GRID/RISICOGRID.txt
        format: NETCDF
        variables:
          - internal_name: V
            name: V
            cluster_mode: Max
            precision: 0
    palettes:
      UMB: /opt/risico/PALETTE/RISICO_UMB.pal
