name: upload lib to crates.io

on:
  release:
    types: [published]

jobs:
  publish-crate:
    name: publish-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_RELEASE_TOKEN }}
