name: upload lib to crates.io

on:
  release:
    types: [published]

jobs:
  release-crate:
    uses: semantic-release-action/rust/.github/workflows/release-library.yml@v5
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_RELEASE_TOKEN }}
